export const metadata = [
  { path: "game/ovo", title: "OvO | Cosmic City" },
  { path: "game/1v1-lol", title: "1v1.LOL | Cosmic City" },
  { path: "game/2048", title: "2048 | Cosmic City" },
  { path: "game/stickman-hook", title: "Stickman Hook | Cosmic City" },
  { path: "game/drift-hunters", title: "Drift Hunters | Cosmic City" },
  { path: "game/basketball-stars", title: "Basketball Stars | Cosmic City" },
  { path: "game/run-3", title: "Run 3 | Cosmic City" },
  { path: "game/cookie-clicker", title: "Cookie Clicker | Cosmic City" },
  { path: "game/slope", title: "Slope | Cosmic City" },
  { path: "game/slope-3", title: "Slope 3 | Cosmic City" },
  {
    path: "game/worlds-hardest-game-3",
    title: "World's Hardest Game 3 | Cosmic City",
  },
  {
    path: "game/friday-night-funkin",
    title: "Friday Night Funkin' | Cosmic City",
  },
  { path: "game/mr-bullet", title: "Mr Bullet | Cosmic City" },
  { path: "game/among-us", title: "Among Us | Cosmic City" },
  { path: "game/moto-x3m", title: "Moto X3M | Cosmic City" },
  { path: "game/bitlife", title: "BitLife | Cosmic City" },
  { path: "game/bottle-flip-3d", title: "Bottle Flip 3D | Cosmic City" },
  { path: "game/color-switch", title: "Color Switch | Cosmic City" },
  { path: "game/google-snake", title: "Google Snake | Cosmic City" },
  { path: "game/color-road", title: "Color Road | Cosmic City" },
  { path: "/", title: "Cosmic City" },
  { path: "games", title: "Cosmic City | Games" },
  { path: "socials", title: "Cosmic City | Socials" },
  { path: "*", title: "404" },
];
